apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: team-one
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-cpu-mem
  namespace: team-one
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-container
  namespace: team-one
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    default:
      cpu: 100m
      memory: 64Mi
    min:
      cpu: 100m
      memory: 64Mi
    max:
      cpu: 1
      memory: 1Gi

